Artificial intelligence conference PR
mprotic123/first-capstone pull request #1
Opened 2021-10-14 15:47 UTC by mprotic123

This is pull request is created in order to review the project "Capstone 1" from Microverse. In this project, I was building an artificial intelligence conference website. Two pages are built for this milestone: Home and About page. Link to a Loom video: [Click here](https://www.loom.com/share/238cf370862e47228bcfbe80b369d8c2?sharedAppSource=personal_library)

**Project requirements**
- Personalize topic
- Design guidelines: colors, typography, layout
- Build two pages: Home & About 
- Build desktop and mobile version
- Interactions: links and mobile menu
- Dynamic page

2021-10-14 18:20 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Milan Protić, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
GitHub flow is followed. :heavy_check_mark:
README is professional. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-14 18:20 UTC, SajjadAhmad14 commented on .github/workflows/linters.yml
> +name: Linters
Please use the linter for HTML, CSS, and JavaScript from [this](https://github.com/microverseinc/linters-config/tree/master/html-css-js) linter config.

2021-10-14 18:20 UTC, SajjadAhmad14 commented on .gitignore
> +test.md
Please add all unnecessary files and folders like `.vscode` to `.gitignore`.

2021-10-14 18:20 UTC, SajjadAhmad14 commented on README.md
>  ## Live Demo
The live demo link in README is broken. Please add an active link here.

2021-10-14 18:20 UTC, SajjadAhmad14 commented on index.html
> +    <footer class="footer">
The footer on the mobile view should have a white background.
Yours:
![footer](https://user-images.githubusercontent.com/35504149/137372756-87cb1ec5-7795-4de5-96a9-ae151731e461.png)
Design:
![footer-o](https://user-images.githubusercontent.com/35504149/137372925-18f1e37d-0e4d-4a99-b197-23bd52a39603.png)

2021-10-14 18:20 UTC, SajjadAhmad14 commented on index.html
> +        <div class="whole-program"><a href="#">SEE THE WHOLE PROGRAM</a></div>
Please use the same color for all the sections of the home page from the design
![see](https://user-images.githubusercontent.com/35504149/137373155-a4a99bda-b8c2-488a-8707-679999223805.png)
.

2021-10-14 18:20 UTC, SajjadAhmad14 commented on index.html
> +      <section class="featured-speakers">
Please follow the design for `Featured speakers` and `partner` sections on the Desktop view.
Your:
![partner-y](https://user-images.githubusercontent.com/35504149/137373498-572850b8-f7d4-4a14-9f05-ad7043fb84f9.png)
Design:

![partners](https://user-images.githubusercontent.com/35504149/137373512-05c28ee0-40aa-4d0c-a752-5c34974cfece.png)
Your:
![feature-y](https://user-images.githubusercontent.com/35504149/137373350-2ccbdeb0-5ea4-4079-8a1c-43046ff58142.png)
Design:
![feature-o](https://user-images.githubusercontent.com/35504149/137373385-def42e16-e96e-4447-9b36-9cf03d43ee8a.png)

2021-10-14 18:20 UTC, SajjadAhmad14 commented on index.html
> +    <nav class="navbar">
The navbar should have the same design for both `About` and `Home` pages on the desktop.
Your:
![nav-y](https://user-images.githubusercontent.com/35504149/137373634-842362a7-dc18-4df4-bc2f-b9de2c354f0e.png)
Design:
![nav-o](https://user-images.githubusercontent.com/35504149/137373675-0c37f839-af18-457c-af87-84ebc9bc0f18.png)

2021-10-15 12:41 UTC, Mihndim2020 requested changes
## Hi @mprotic123, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)

 # Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 12:41 UTC, Mihndim2020 commented on index.html
> +      <section class="featured-speakers">
- [ ] As requested by the previous code reviewer which is also a requirement for this project, please make sure the feature speakers section is implemented as in the design, the design has two columns for the desktop version. Please kindly fix that.

2021-10-15 12:54 UTC, mprotic123 commented on index.html
> +      <section class="featured-speakers">
Hi, @Mihndim2020 ! I am so sorry sir but I'm not sure that I understand what is wrong. Can you please explain it to me? 
![Screenshot_1](https://user-images.githubusercontent.com/82707385/137490048-f0f7ef6c-e07f-4310-8be2-51068faeb9ed.png)

2021-10-15 14:48 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Milan Protić, 
 ### Thank you for working on the changes suggested previously. :ok_hand:

## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-15 14:48 UTC, SajjadAhmad14 commented on index.html
> +      <section class="featured-speakers">
`Featured Speakers` should be the same as in the design. So you can implement it using Grid. There are two columns and three rows in the design. You may have two rows and two columns. So kindly see [this](https://www.w3schools.com/css/css_grid.asp) resource and implement it.

2021-10-16 10:59 UTC, rukundoeric approved these changes
Hi @mprotic123,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-16 11:09 UTC, merged